package com.socialmedia.event;

import com.socialmedia.dto.NotificationDTO;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Tests for the {@link NotificationEvent} class generated by Lombok.
 * <p>
 * This class ensures that the {@link NotificationEvent} class functions correctly,
 * including its constructors, getters, and setters.
 * </p>
 *
 * @version 1.0
 * @since 2025-01-28
 */
class NotificationEventTest {

    /**
     * Tests the no-argument constructor of NotificationEvent.
     * Verifies that a new instance is created with default values.
     */
    @Test
    @DisplayName("Test NotificationEvent no-args constructor")
    void testNoArgsConstructor() {
        // Act: Create a new instance using the no-args constructor
        NotificationEvent event = new NotificationEvent();

        // Assert: Verify that the instance is not null and fields are initialized correctly
        assertNotNull(event, "NotificationEvent instance should not be null after no-args constructor");
        assertNull(event.getNotification(), "Notification should be null if not explicitly set");
    }

    /**
     * Tests the all-arguments constructor of NotificationEvent.
     * Verifies that fields are initialized correctly with provided values.
     */
    @Test
    @DisplayName("Test NotificationEvent all-args constructor")
    void testAllArgsConstructor() {
        // Arrange: Create a sample NotificationDTO
        NotificationDTO dto = new NotificationDTO(1L, "New notification", 2L, false);

        // Act: Create a new instance using the all-args constructor
        NotificationEvent event = new NotificationEvent(dto);

        // Assert: Verify that the fields are set correctly
        assertNotNull(event, "NotificationEvent instance should not be null after all-args constructor");
        assertEquals(dto, event.getNotification(), "Notification in event should match the one passed to constructor");
    }

    /**
     * Tests the setter method of NotificationEvent.
     * Verifies that the notification field is updated correctly.
     */
    @Test
    @DisplayName("Test NotificationEvent setNotification method")
    void testSetNotification() {
        // Arrange: Create a new instance and a sample NotificationDTO
        NotificationEvent event = new NotificationEvent();
        NotificationDTO dto = new NotificationDTO(2L, "Another notification", 3L, true);

        // Act: Set the notification using the setter method
        event.setNotification(dto);

        // Assert: Verify that the notification field is updated correctly
        assertEquals(dto, event.getNotification(), "Setter should update the notification field correctly");
    }

    /**
     * Tests the getter method of NotificationEvent.
     * Verifies that the notification field is retrieved correctly.
     */
    @Test
    @DisplayName("Test NotificationEvent getNotification method")
    void testGetNotification() {
        // Arrange: Create a new instance and set a NotificationDTO
        NotificationEvent event = new NotificationEvent();
        NotificationDTO dto = new NotificationDTO(10L, "Test get", 99L, false);
        event.setNotification(dto);

        // Act: Retrieve the notification using the getter method
        NotificationDTO retrieved = event.getNotification();

        // Assert: Verify that the getter returns the correct DTO
        assertEquals(dto, retrieved, "Getter should return the same DTO that was set");
    }
}
